services:
  gateway_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: gateway_prod
    ports:
      - "4000:4000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
