services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "9000:9000"
    networks:
      - ekoru-network
    volumes:
      - /home/ekoru/images:/home/ekoru/images

networks:
  ekoru-network:
    external: true
